import { listCurrencies, listRewards } from '@/services/adminRepository';
import { createCurrencyAction, createRewardAction, publishRewardAction } from '@/app/actions/content';
import StatusBadge from '@/components/StatusBadge/StatusBadge';
import styles from '@/app/section.module.css';

export default async function EconomyPage({ searchParams }) {
  const params = await searchParams; const [currencies, rewards] = await Promise.all([listCurrencies(), listRewards()]);
  return <div className={styles.page}>
    <div className={styles.header}><div><h2>Economia & Recompensas</h2><p>Moedas, saldos e rewards são server-authoritative. O navegador nunca define o próprio saldo nem concede a própria recompensa.</p></div></div>
    {params?.created && <div className={styles.notice}>Conteúdo econômico criado.</div>}{params?.published && <div className={styles.notice}>Recompensa publicada.</div>}{params?.error && <div className={styles.error}>{params.error}</div>}
    <section className={styles.panel}><h3>Nova moeda</h3><form className={styles.form} action={createCurrencyAction}><div className={styles.formGrid}><input name="id" placeholder="id: juris" required/><input name="name" placeholder="Nome: Juris" required/><input name="symbol" placeholder="Símbolo: JR" required/><select name="currencyType"><option value="common">Comum</option><option value="premium">Premium</option><option value="special">Especial</option></select></div><button className={styles.primary}>Criar e publicar moeda</button></form></section>
    <section className={styles.panel}><h3>Moedas</h3>{currencies.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>ID</th><th>Nome</th><th>Tipo</th><th>Status</th></tr></thead><tbody>{currencies.map(c => <tr key={c.id}><td>{c.id}</td><td><strong>{c.name}</strong> ({c.symbol})</td><td>{c.currency_type}</td><td><StatusBadge status={c.status}/></td></tr>)}</tbody></table></div> : <div className={styles.empty}>Nenhuma moeda.</div>}</section>
    <section className={styles.panel}><h3>Nova recompensa</h3><form className={styles.form} action={createRewardAction}><div className={styles.formGrid}><input name="id" placeholder="id: primeiro_caso" required/><input name="name" placeholder="Nome" required/><input name="triggerType" placeholder="Trigger: case_completed" required/><select name="claimPolicy"><option value="once">Uma vez</option><option value="per_case">Por caso</option><option value="daily">Diária</option></select></div><textarea name="conditions" defaultValue={'{\n  "minCasesSolved": 1\n}'} required/><textarea name="reward" defaultValue={'{\n  "xp": 50,\n  "currencies": { "creditos": 100 }\n}'} required/><button className={styles.primary}>Salvar recompensa em draft</button></form></section>
    <section className={styles.panel}><h3>Recompensas</h3>{rewards.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>ID</th><th>Nome</th><th>Trigger</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rewards.map(r => <tr key={r.id}><td>{r.id}</td><td><strong>{r.name}</strong></td><td>{r.trigger_type}<br/>{r.metadata?.claimPolicy || 'once'}</td><td><StatusBadge status={r.status}/></td><td>{r.status === 'draft' ? <form action={publishRewardAction}><input type="hidden" name="id" value={r.id}/><button className={styles.secondary}>Publicar</button></form> : '—'}</td></tr>)}</tbody></table></div> : <div className={styles.empty}>Nenhuma recompensa.</div>}</section>
  </div>;
}
